[W.I.P.]Spring boot program
dezuz/Homework23 pull request #1
Opened 2019-06-10 14:43 UTC by dezuz

2019-06-11 07:13 UTC, Taniann requested changes
please resolve comments

2019-06-11 07:13 UTC, Taniann commented on src/main/java/com/mateacademy/controller/ApplicationController.java
> +    @Autowired
better use constructor di

2019-06-11 07:13 UTC, Taniann commented on src/main/java/com/mateacademy/controller/UserController.java
> +import org.springframework.web.bind.annotation.*;
dont use wild card imports

2019-06-11 07:13 UTC, Taniann commented on src/main/java/com/mateacademy/model/BaseModel.java
> +import javax.persistence.*;
the same about wild card import

2019-06-11 07:13 UTC, Taniann commented on src/main/java/com/mateacademy/service/ProducerServiceImpl.java
> +    @Autowired
better use constructor di

2019-06-11 07:13 UTC, Taniann commented on src/main/java/com/mateacademy/service/UserServiceImpl.java
> +    @Autowired
you can use lombok annotations for these purpose

2019-06-15 16:36 UTC, dezuz commented on src/main/java/com/mateacademy/controller/ApplicationController.java
> +    @Autowired
For me, it's better to use @Autowired

2019-06-17 09:07 UTC, Taniann commented on src/main/java/com/mateacademy/configuration/SecurityConfig.java
> +//package com.mateacademy.configuration;
remove it from your PR

2019-06-28 11:40 UTC, merged